title: pello.io
author: Pello Altadill
email: p_at_pello_dot_io
description: > # this means to ignore newlines until "baseurl:"
  Pello Xabier Altadill Izura´s personal site, programming, projects, code samples,
  guides, tricks,...

twitter_username: pello_io
github_username:  pxai

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

paginate: 10
# system variables, do not change unless you knew what's it does.
paginate_path: page/:num

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll-octicons
